require(GenomicFeatures)
require(RCurl)
require(stringr)

# Suggestions
# table = "knownGene", "ncbiRefSeq"
fetchKnownGenes <- function(genome="hg19", table="ncbiRefSeq") {
  # Find urls and check if exists
  url <- "http://hgdownload.cse.ucsc.edu/goldenPath/"
  sqlurl <- paste0(url, genome, "/database/", table,".sql")
  taburl <- paste0(url, genome, "/database/", table,".txt.gz")
  if(!url.exists(sqlurl) | !url.exists(taburl)) {
    message("Error: cannot find table for genome!")
    return()
  }
  # Get column names from sql
  sqlcon <- url(sqlurl)
  sql <- readLines(sqlcon)
  colnm <- str_match(grep("(NOT|DEFAULT) NULL", sql, value = T), "`(.+)`")[,2]
  # Get table
  con <- gzcon(url(taburl))
  txt <- readLines(con)
  tab <- read.table(textConnection(txt), sep="\t", header = FALSE)
  close(sqlcon); close(con)
  if(ncol(tab) == length(colnm)) {
    colnames(tab) <- colnm
  } else {
    message("Unable to determine column names, returning raw data table...")
    return(tab)
  }
  # Convert to granges
  gr <- try(GRanges(tab), silent = TRUE)
  if("try-error" %in% class(gr)) {
    colnames(tab) <- gsub("^txStart$", "start", colnames(tab))
    colnames(tab) <- gsub("^txEnd$", "end", colnames(tab))
    gr <- try(GRanges(tab), silent = TRUE)
    if("try-error" %in% class(gr)) {
      message("Unable to convert to granges, returning data.frame...")
      return(tab)
    }
  }
  # Formatting for ensembl genes (ensGene) table
  if (table == "ensGene") {
    gr <- convert_ensgene_to_symbol(gr, organism = genome)
  }
  return(gr)
}


GetNearestGeneSymbol <- function (granges, genes=NULL, genome = "hg19") {
  if (is.null(genes)) {
    genes <- fetchKnownGenes(genome)
  }
  distance <- distanceToNearest(granges, genes)
  mygenes <- as.character(genes$name2)[to(distance)]
  return(data.frame(genes=mygenes, distance=values(distance)$distance))
}

biomaRt_UCSC_to_Symbol <- function(ids, organism = "hsapiens") {
  require(biomaRt)
  mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
  res <- getBM(c("ucsc","hgnc_symbol"), filters = "ucsc", values = ids, mart = mart)
  res <- res[match(genes, res$ucsc), "hgnc_symbol"]
}

#' 
#' @param gr        granges object with ensembl gene names in column name2
#'                  generated by fetchKnownGenes(genome, table="ensgene")
#' @param organism  organism name used in ensembl dataset
#'                  also accepts genome build short form
#'                  use listDatasets() to find organism name
#'                  common organisms: hsapiens, mmusculus, rnorvegicus, sscrofa
#' @param symbol    symbol to be converted to
#'                  examples: hgnc_symbol, external_gene_name
#' @param exclude   (T/F) remove genes without associated symbol
#' 
#' @return gr with name2 substituted for symbol
convert_ensgene_to_symbol <- function(gr, organism = "hsapiens", symbol="external_gene_name", exclude=TRUE) {
  require(biomaRt)
  # Organism table (convert from genome to organism)
  orgnames <- c("hg19"="hsapiens", "hg38"="hsapiens", "rn6"="rnorvegicus", "mm10"="mmusculus", "susScr11"="sscrofa")
  if(!is.na(orgnames[organism])) organism <- orgnames[organism]
  # Download annotations from biomaRt
  mart <- useMart("ensembl", dataset = paste0(organism, "_gene_ensembl"))
  genes <- getBM(c("ensembl_gene_id", symbol), mart = mart)
  # Overwrite name2 with symbol
  gr2 <- gr
  gr2$name2 <- genes[match(gsub("\\..*", "", as.character(gr$name2)), genes[,1]),2]
  # Exclude genes without symbol
  if(exclude) gr2 <- gr2[!gr2$name2 %in% ""]
  return(gr2)
}

